### ISSUE TITLE
Set up a build job

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-windows#1]
It would be good if we were able to build a binary from the sources on our Jenkins on cloudbees (https://openhab.ci.cloudbees.com/).

Not sure if Cloudbees supports the infrastructure to do this, but we should at least check this out.
##

**Comment by Alex-Witkowski** [comment]
This is not possible with the actual configuration. 

You would need to have at least one windows build node. Do you have CI for the iOS App? 

Maybe you could use Team Foundation Services for that.

**Comment by NicoVermeir** [comment]
maybe we could use AppVeyor? We're using it for XAML Styler and it seems to work pretty well.
they have a free plan for OSS projects
https://www.appveyor.com/pricing/

@kaikreuzer what do you think?

**Comment by cniweb** [comment]
I think AppVeyor is a good idea!
I have a appveyor.yml example here:
https://github.com/cniweb/openhabUWP/blob/master/appveyor.yml

**Comment by cniweb** [comment]
I make a PR #52 
Build results can you found here:
https://ci.appveyor.com/project/cniweb/openhab-windows
