### ISSUE TITLE
App crashes if not able to load Sitemap

### ISSUE THREAD

**Issue by cd-tronic** [openhab/openhab-windows#114]
I've got a Sitemap (i think there is something wrong with it - however using a webbrowser it work's great) that crashes the app if I try to navigate to it.
That is not a real issue as I think it is Sitemap related - I have to look at it closer.

The real issue is, that since the last update the last sitemap get's load on Appstart. Now I can't navigate to another Sitemap anymore.

I will have a look at it the next days and try to fix

**Comment by NicoVermeir** [comment]
any chance you could share your sitemap? I could use it to make the app not crash if it tries to load a defunct sitemap

**Comment by cd-tronic** [comment]
Hello Nico,
check out the attachment. 
This was just a testsitemap which i used to play around with the artnet plugin. I think artnet isn't installed at the moment. This might be why the app crashes. Maybe I have some time to clone the Repo an check out the problem the next days. 
[DMX.txt](https://github.com/openhab/openhab.windows/files/1506517/DMX.txt)

I just wanted to add this issue. I think it would be better to add an try{}catch{} which throws an exception dialog and reset's the last used sitemap to a default page if something goes wrong on sitemap loading.

**Comment by gerritv** [comment]
I would like to help fix this but need to know how to communicate to the user that there is a problem. openHabException() doesn't display anything to user.

I added `            catch (System.Net.Http.HttpRequestException)
            {
                return false;
            }`

at 251 in OpenHAB.cs, which fixes the crash. (dev branch).
Related to this is that when the Save button is clicked and the URL is reachable, the SetVaidUrl() returns false at 210, thus preventing a reload of the sitemap. Adding `return true;` at 210 solves that as well. So now you don't crash on a bad URL and you get to reload a changed sitemap. 
If this is actually a separate issue I am happy to submit one.

**Comment by gerritv** [comment]
Re: dmx.sitemap, the Switch widget is getting a null Item, thus a NullReferenceException. (Line 52 of SwitchWidgetXaml.cs.
I guess one fix to protect from this (likely common error during sitemap development) is to add a check to each widget for null Item. on entry to SetState(). And show an error to user

**Comment by NicoVermeir** [comment]
@gerritv great that you want to help out!

there's currently only one point where the user gets notified of an error and that's when you enter an invalid url in the settings. although I'm not very happy with the way that the notification happens.

maybe we should switch to an actual Windows notification? What do you think?

**Comment by gerritv** [comment]
Yes, I think a 'proper' message is the best way. 
https://msdn.microsoft.com/en-us/library/windows/apps/hh738363.aspx

I think a class to display/await for answer/return answer is the clean way. First I will however do a Pull for the above fixes, might be a day or so while I figure that out, not a fan of Git,
