### ISSUE TITLE
Openhab 2.2

### ISSUE THREAD

**Issue by cd-tronic** [openhab/openhab-windows#119]
Sitemaps don't load using Openhab 2.2

**Comment by NicoVermeir** [comment]
works fine here, can you give a bit more detail on your setup?

**Comment by cd-tronic** [comment]
Okay!. I will do some further testing.
Myopenhab seems to work fine - i can open the  openhabfrontend using myopenhab website.

The setup worked fine with 2.1. 

I will check my sitemaps and get back to you.

**Comment by cd-tronic** [comment]
Hi Nico,
doesn't seem to be a problem with my sitemaps. I just forked a version of Openhab.Windows for me and tried to find the error.
Can you tell me how Openhab catches the sitemaps after launching the app?
I can't find a "get sitemap" or something like this function. Maybe you could give me a hint how this works in the openhab app.

**Comment by NicoVermeir** [comment]
OpenHAB.Core.ViewModel.MainViewModel
line 158 does the call for loading sitemaps

**Comment by cd-tronic** [comment]
Hi Nico,
well Sitemaps don't load cause OpenHABVersion is "OpenHABVersion.None".
OpenhabHTTPclient is null (OpenHAB.cs line 61)

CheckUrlReachalbility Function gives me a "false" back for result in (OpenHAB.cs Line240).

So seems to be a problem with my Openhab configuration, right?

**Comment by hoffe86** [comment]
Hi @cd-tronic 
Can you check if this bug is solved with the latest store version?

**Comment by cd-tronic** [comment]
Hi @hoffe86,

In fact it worked before also. But i can't remember what the Problem was.
I think something had been wrong with my sitemap. But i'm not sure any more. I will close this. 

It was great to see an update for openhab App in Windows store! 😊
