### ISSUE TITLE
Project loading error AND build failures

### ISSUE THREAD

**Issue by jp54l** [openhab/openhab-windows#123]
Hi

I'm having issues trying to load and build the project in VS 2015 Update 3.

![image](https://user-images.githubusercontent.com/15167253/56093492-d0de8100-5f0c-11e9-8897-9b08d1a3404f.png)

Initially the project would not load in VS 2015 requesting an update required. Selecting download update took me to main VS download page, which only showed the latest tools.....not a specific download or update for the project.

I got around this by editing the Min and target csproj file like this....

![image](https://user-images.githubusercontent.com/15167253/56093527-40547080-5f0d-11e9-8631-ae7ffb467d3c.png)

I have installed both UWP SDKs as recommended, but the problem persists.

Do I need a later VS version?

**Comment by hoffe86** [comment]
Hi @jp54l 
Visual Studio 2019 is working for me
https://visualstudio.microsoft.com/vs/

**Comment by hoffe86** [comment]
Project is updated to VS 2019 -> Close issue
