### ISSUE TITLE
Crash when Sitemap item contains Humidity icon

### ISSUE THREAD

**Issue by Cossey** [openhab/openhab-windows#139]
openHAB UWP crashes straight to desktop when attempting to load my primary sitemap file. 

Issue appears to be the Humidity Icon being used in the sitemap; it could be possible it is related to a colour profile error with this image.

Crash occurs in class `ImageLabel.xaml.cs` in function:
```
private static void IconChangedCallback(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs)
```
With Error: `System.ArgumentException: 'Value does not fall within the expected range.'` 
Image: `http://<redacted>:8080/icon/humidity?state=58.26 %&format=png`

I've try/catched the code in the function and it does end up loading the sitemap without crashing (albeit without displaying the humidity icon, but all other icons I use appear to display fine).

Seems like it may have been possible in the .net framework to use `bi.CreateOptions |= BitmapCreateOptions.IgnoreColorProfile` to ignore colour profile errors however this does not appear to be available in the UWP `BitmapImage` class.

_openHAB 2.5.0.M2 Milestone Build running in Docker on a Raspberry Pi 3._

**Comment by cd-tronic** [comment]
Hi @Cossey ,

i think this has something to to with the image state. 
I'm not sure if this is completely integrated at all. I know that they work but i think i had a simmilar problem with an Icon using states some time ago. 
Can you try to edit the url and remove the space before the %.

Set a breakpoint and try to edit the url before you move on.
I'm pretty busy at the moment but i will try to have a look at it, too.

**Comment by Cossey** [comment]
I've already tried this previously, the space between the value and percentage is fine and have tested this with the space removed and have also tested the original URL with the space in a web browser without issue. I'm sure its something with that specific image.

Other images in openHAB that I don't use in my sitemaps might exhibit a similar problem. Happy to assist with this, since this is holding me back using this app on my PC and Xbox.

**Comment by cd-tronic** [comment]
Hi @ Cossey,

i found that the issue was the '%' character in the url. I added some Regex handling to clean the sate.
See PR #140

**Comment by Cossey** [comment]
Ah I see. The % is used for encoding special characters in url and likely causing issues. 
Thanks for resolving this, great to see this app getting worked on.

**Comment by Cossey** [comment]
Closing this issue due to PR being merged.
