### ISSUE TITLE
App crashing when accessing All Items Sitemap

### ISSUE THREAD

**Issue by maedball** [openhab/openhab-windows#150]
Instead of opening my personal sitemap the App opens the all items (internal) sitemap and crashes. The issue can be workaround ed by deleting all items in openhab, changing to the personal sitemap and adding all items again.

This is the error message thrown by the Windows Event viewer.

Version=1
EventType=MoAppCrash
EventTime=132312730681920888
ReportType=2
Consent=1
UploadTime=132312730684011640
ReportStatus=268435456
ReportIdentifier=9dd32310-6fe0-4b92-9ffd-fab5071a239d
IntegratorReportIdentifier=6714deb3-bada-431f-8f10-7ac9f32a327c
Wow64Host=34404
NsAppName=praid:App
OriginalFilename=OpenHAB.Windows.exe
AppSessionGuid=00003fa8-0001-0038-5adc-063fba11d601
TargetAppId=U:openHABFoundatione.V.openHAB_2019.12.7.0_x64__va1j9qbqnd8h6!App
TargetAppVer=2019.12.7.0_x64_!2019//12//07:21:28:03!0!OpenHAB.Windows.exe
BootId=4294967295
ServiceSplit=1545859489
TargetAsId=4221
UserImpactVector=808452912
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=1660d9ebc57299234854dfd8d51cd89f
Response.BucketTable=5
Response.LegacyBucketId=1753272277335333023
Response.type=4
Sig[0].Name=Package Full Name
Sig[0].Value=openHABFoundatione.V.openHAB_2019.12.7.0_x64__va1j9qbqnd8h6
Sig[1].Name=Application Name
Sig[1].Value=praid:App
Sig[2].Name=Application Version
Sig[2].Value=1.0.0.0
Sig[3].Name=Application Timestamp
Sig[3].Value=5dec1963
Sig[4].Name=Fault Module Name
Sig[4].Value=combase.dll
Sig[5].Name=Fault Module Version
Sig[5].Value=10.0.18362.693
Sig[6].Name=Fault Module Timestamp
Sig[6].Value=1fabb0ef
Sig[7].Name=Exception Code
Sig[7].Value=80070057
Sig[8].Name=Exception Offset
Sig[8].Value=000000000007cd5a
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.18363.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0ddf
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0ddf90aab2f2fd87818d32a9200cbdb3
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=4864
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=4864418ea533c9eaacf00fb9648268af
UI[2]=C:\Program Files\WindowsApps\openHABFoundatione.V.openHAB_2019.12.7.0_x64__va1j9qbqnd8h6\OpenHAB.Windows.exe
LoadedModule[0]=C:\Program Files\WindowsApps\openHABFoundatione.V.openHAB_2019.12.7.0_x64__va1j9qbqnd8h6\OpenHAB.Windows.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Program Files\WindowsApps\openHABFoundatione.V.openHAB_2019.12.7.0_x64__va1j9qbqnd8h6\OpenHAB.Windows.dll
LoadedModule[5]=C:\Windows\System32\crypt32.dll
LoadedModule[6]=C:\Windows\System32\ucrtbase.dll
LoadedModule[7]=C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.27912.0_x64__8wekyb3d8bbwe\SharedLibrary.dll
LoadedModule[8]=C:\Windows\System32\MSASN1.dll
LoadedModule[9]=C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe\mrt100_app.dll
LoadedModule[10]=C:\Windows\System32\ole32.dll
LoadedModule[11]=C:\Windows\System32\advapi32.dll
LoadedModule[12]=C:\Windows\System32\combase.dll
LoadedModule[13]=C:\Windows\System32\msvcrt.dll
LoadedModule[14]=C:\Windows\System32\RPCRT4.dll
LoadedModule[15]=C:\Windows\System32\sechost.dll
LoadedModule[16]=C:\Windows\System32\GDI32.dll
LoadedModule[17]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[18]=C:\Windows\System32\win32u.dll
LoadedModule[19]=C:\Windows\System32\gdi32full.dll
LoadedModule[20]=C:\Windows\System32\BCrypt.dll
LoadedModule[21]=C:\Windows\System32\msvcp_win.dll
LoadedModule[22]=C:\Windows\System32\ws2_32.dll
LoadedModule[23]=C:\Windows\System32\USER32.dll
LoadedModule[24]=C:\Windows\System32\OleAut32.dll
LoadedModule[25]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\VCRUNTIME140_APP.dll
LoadedModule[26]=C:\Windows\System32\Normaliz.dll
LoadedModule[27]=C:\Windows\SYSTEM32\ncrypt.dll
LoadedModule[28]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[29]=C:\Windows\SYSTEM32\iphlpapi.dll
LoadedModule[30]=C:\Windows\SYSTEM32\sspicli.dll
LoadedModule[31]=C:\Windows\SYSTEM32\NTASN1.dll
LoadedModule[32]=C:\Windows\SYSTEM32\DPAPI.DLL
LoadedModule[33]=C:\Windows\SYSTEM32\mrt100.dll
LoadedModule[34]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[35]=C:\Windows\System32\rmclient.dll
LoadedModule[36]=C:\Windows\System32\IMM32.DLL
LoadedModule[37]=C:\Windows\SYSTEM32\twinapi.appcore.dll
LoadedModule[38]=C:\Windows\System32\shcore.dll
LoadedModule[39]=C:\Windows\System32\Windows.UI.Xaml.dll
LoadedModule[40]=C:\Windows\SYSTEM32\CoreMessaging.dll
LoadedModule[41]=C:\Windows\SYSTEM32\Bcp47Langs.dll
LoadedModule[42]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[43]=C:\Windows\SYSTEM32\dcomp.dll
LoadedModule[44]=C:\Windows\System32\Windows.UI.dll
LoadedModule[45]=C:\Windows\SYSTEM32\TextInputFramework.dll
LoadedModule[46]=C:\Windows\SYSTEM32\InputHost.dll
LoadedModule[47]=C:\Windows\SYSTEM32\CoreUIComponents.dll
LoadedModule[48]=C:\Windows\SYSTEM32\PROPSYS.dll
LoadedModule[49]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[50]=C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
LoadedModule[51]=C:\Windows\system32\uxtheme.dll
LoadedModule[52]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[53]=C:\Windows\System32\windows.storage.dll
LoadedModule[54]=C:\Windows\System32\profapi.dll
LoadedModule[55]=C:\Windows\System32\powrprof.dll
LoadedModule[56]=C:\Windows\System32\UMPDC.dll
LoadedModule[57]=C:\Windows\System32\shlwapi.dll
LoadedModule[58]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[59]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[60]=C:\Windows\SYSTEM32\dxcore.dll
LoadedModule[61]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[62]=C:\Windows\System32\MrmCoreR.dll
LoadedModule[63]=C:\Windows\SYSTEM32\windows.staterepositorycore.dll
LoadedModule[64]=C:\Windows\System32\NSI.dll
LoadedModule[65]=C:\Windows\SYSTEM32\bcp47mrm.dll
LoadedModule[66]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[67]=C:\Windows\System32\DriverStore\FileRepository\7_lenovo_iigd_dch.inf_amd64_6d465b1b41136044\igd10iumd64.dll
LoadedModule[68]=C:\Windows\System32\DriverStore\FileRepository\7_lenovo_iigd_dch.inf_amd64_6d465b1b41136044\igdgmm64.dll
LoadedModule[69]=C:\Windows\System32\DriverStore\FileRepository\7_lenovo_iigd_dch.inf_amd64_6d465b1b41136044\igc64.dll
LoadedModule[70]=C:\Windows\System32\shell32.dll
LoadedModule[71]=C:\Windows\System32\cryptsp.dll
LoadedModule[72]=C:\Windows\SYSTEM32\dwrite.dll
LoadedModule[73]=C:\Windows\System32\Windows.Globalization.dll
LoadedModule[74]=C:\Windows\System32\msctf.dll
LoadedModule[75]=C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll
LoadedModule[76]=C:\Windows\system32\execmodelproxy.dll
LoadedModule[77]=C:\Windows\SYSTEM32\d2d1.dll
LoadedModule[78]=C:\Windows\System32\UiaManager.dll
LoadedModule[79]=C:\Windows\SYSTEM32\windows.ui.core.textinput.dll
LoadedModule[80]=C:\Windows\System32\Windows.UI.Immersive.dll
LoadedModule[81]=C:\Windows\system32\DataExchange.dll
LoadedModule[82]=C:\Windows\SYSTEM32\rometadata.dll
LoadedModule[83]=C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe\Microsoft.Services.Store.Engagement.dll
LoadedModule[84]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\vccorlib140_app.DLL
LoadedModule[85]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\CONCRT140_APP.dll
LoadedModule[86]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\MSVCP140_APP.dll
LoadedModule[87]=C:\Windows\System32\Windows.Storage.ApplicationData.dll
LoadedModule[88]=C:\Windows\System32\Windows.Networking.Connectivity.dll
LoadedModule[89]=C:\Windows\System32\Windows.Networking.HostName.dll
LoadedModule[90]=C:\Windows\System32\Windows.Web.Http.dll
LoadedModule[91]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[92]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[93]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[94]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[95]=C:\Windows\SYSTEM32\WININET.dll
LoadedModule[96]=C:\Windows\SYSTEM32\TOKENBINDING.dll
LoadedModule[97]=C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[98]=C:\Windows\SYSTEM32\winhttp.dll
LoadedModule[99]=C:\Windows\system32\mswsock.dll
LoadedModule[100]=C:\Windows\SYSTEM32\firewallapi.dll
LoadedModule[101]=C:\Windows\SYSTEM32\fwbase.dll
LoadedModule[102]=C:\Windows\System32\Windows.ApplicationModel.dll
LoadedModule[103]=C:\Windows\SYSTEM32\Windows.UI.Xaml.Controls.dll
LoadedModule[104]=C:\Windows\system32\mlang.dll
LoadedModule[105]=C:\Windows\system32\directmanipulation.dll
LoadedModule[106]=C:\Windows\System32\threadpoolwinrt.dll
LoadedModule[107]=C:\Windows\system32\windowscodecs.dll
LoadedModule[108]=C:\Windows\System32\Windows.Graphics.dll
LoadedModule[109]=C:\Windows\SYSTEM32\wuceffects.dll
LoadedModule[110]=C:\Windows\SYSTEM32\PhotoMetadataHandler.dll
LoadedModule[111]=C:\Windows\system32\windowscodecsext.dll
LoadedModule[112]=C:\Windows\SYSTEM32\mscms.dll
LoadedModule[113]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[114]=C:\Windows\SYSTEM32\ColorAdapterClient.dll
LoadedModule[115]=C:\Windows\SYSTEM32\icm32.dll
LoadedModule[116]=C:\Windows\SYSTEM32\profext.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18363
OsInfo[3].Key=ubr
OsInfo[3].Value=752
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=211503
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.719.18362.0-11.0.180
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=65238
OsInfo[19].Key=svolsz
OsInfo[19].Value=953
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.752.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=MoAppCrash
AppName=OpenHAB.Windows
AppPath=C:\Program Files\WindowsApps\openHABFoundatione.V.openHAB_2019.12.7.0_x64__va1j9qbqnd8h6\OpenHAB.Windows.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=19E7860748DE6F3B95CD08287D22FE3C
MetadataHash=-20502169

Here you see my personal two sitemaps + the internal one which just lists all devices.
![image](https://user-images.githubusercontent.com/23019308/79144345-199a7580-7dbf-11ea-96a7-114a14c6414d.png)

**Comment by hoffe86** [comment]
@maedball Thanks for reporting. I will check that and will come back to you if need additional information

**Comment by hoffe86** [comment]
Hi @maedball
We released a new version for the Beta App.
https://www.microsoft.com/store/apps/9N140MD0NJ6T

Can you check if the error is also occurring there?

**Comment by maedball** [comment]
Looking very good, no default sitemap anymore.

Now I just need to fix my newly created sitemap (played to much with openhab3 and introduced several bugs). By now I had no time to fix it.

Once I fixed the it I will reconfirm that everything is running as expected.

**Comment by maedball** [comment]
After fixing the issues (and there were a lot ;-)). All seems to be working very good!!!!

Thank you very much for the fixes ;-)

**Comment by hoffe86** [comment]
Okay sound good.
I will close the issue
