### ISSUE TITLE
Bug with loading data... not set to invisible after changeing sitemap

### ISSUE THREAD

**Issue by cd-tronic** [openhab/openhab-windows#157]
@hoffe86 
are you aware that there is an bug at the moment in release/beta where the "Loading Data..." overlay doesn't get invisible after switching the sitemap even if all widgets are load?
It works when the app get's started. But doesn't stop showing the loading bar after switching sitemap.

I got this issue and also got the info from a friend that he is experiencing the same problem

**Comment by hoffe86** [comment]
Thanks for hint.
I will check it

**Comment by cd-tronic** [comment]
Hi @hoffe86 ,

did you check this? Or can you give me an advise where the "loading data..." overlay should get disabled? It's pretty annoying to restart the app every time after switching the sitemap.

Something else: When does the Microsoft Store get the Updated Beta Versions. Looks like there is no automation for this? My Tablet and some guys around me are waiting for it :)

**Comment by hoffe86** [comment]
Hey @cd-tronic,
Issue is fixed and merged to beta branch. Can you confirm the fix on your side?

I will publish a new beta app release asap when your pending PRs are closed and this issue is also merged into the Beta branch.

**Comment by cd-tronic** [comment]
Hi @hoffe86,

i will check this out today evening or tomorrow.

Thanks!

**Comment by cd-tronic** [comment]
Hi @hoffe86,

Bug is fixed!
