### ISSUE TITLE
Not working with openHAB 3.1.0.M5

### ISSUE THREAD

**Issue by Shituation** [openhab/openhab-windows#192]
The app fails to show the controls showing the error: "Not able to parse runtime verion from openHAB server"

![Captura de pantalla 2021-06-20 122953](https://user-images.githubusercontent.com/43975882/122679960-6946af00-d1c3-11eb-83c0-54db976c3a98.jpg)
![Captura de pantalla 2021-06-20 123035](https://user-images.githubusercontent.com/43975882/122679961-6a77dc00-d1c3-11eb-812e-c1e4dd9af50d.jpg)

**Comment by cd-tronic** [comment]
Hi @elcosomalo1 ,

i got the same issue since updating to 3.1.0M5.

I will have a look at it within the next days.

Regards

**Comment by cd-tronic** [comment]
@elcosomalo1 just a small issue. Took some time to get my Openhab solution up and running after switchting to a new PC.

**Comment by Shituation** [comment]
> @elcosomalo1 just a small issue. Took some time to get my Openhab solution up and running after switchting to a new PC.

I tried reinstalling the app today but it still shows the error.

**Comment by cd-tronic** [comment]
@elcosomalo1 yes. unfortunately @hoffe86 has to review and merg the changes first and then upload the new version to Windows Store.
Stay tuned. Hopefully won't take too long.

**Comment by cd-tronic** [comment]
@elcosomalo1 
OH3.1 is offical out right now. It should work again after updateing OH to the release version. The problem in the app is that the 'M' in '3.1.0.M5' (Milestone 5) can't be parsed to a Version correctly.

**Comment by Shituation** [comment]
> @elcosomalo1
> OH3.1 is offical out right now. It should work again after updateing OH to the release version. The problem in the app is that the 'M' in '3.1.0.M5' (Milestone 5) can't be parsed to a Version correctly.

OK! going to try that!  thanks for everything!

**Comment by cd-tronic** [comment]
> > @elcosomalo1
> > OH3.1 is offical out right now. It should work again after updateing OH to the release version. The problem in the app is that the 'M' in '3.1.0.M5' (Milestone 5) can't be parsed to a Version correctly.
> 
> OK! going to try that! thanks for everything!

you're welcome. Thanks for reporting the issue

**Comment by hoffe86** [comment]
Hey @elcosomalo1 @cd-tronic 
Sorry for writing so late, but the last months were really challenging at work.
But now I have vacation and more time for the project ;-)

I will have look on the PR to fix error for the upcoming milestone releases.
