### ISSUE TITLE
SwitchWidget should use styled framework control like ToggleSwitch 

### ISSUE THREAD

**Issue by Alex-Witkowski** [openhab/openhab-windows#44]
So it would be easy to update values and perform actions with databinding.

**Comment by NicoVermeir** [comment]
agreed, I tried going this way at first but the template was pretty heavy to style to look like this. so this was a faster way to get a switch going. but should definitely be replaced in the future

**Comment by cd-tronic** [comment]
do you talk about the toggle Widget? In fact I don't like it that much 'cause I think it's not that intuitive than the standard UWP-Toggle. I always have to think about it to know if it is in ON or OFF state.
Just my opinion.

**Comment by hoffe86** [comment]
Functionality is implemented and will be available in the [Beta app](https://www.microsoft.com/store/apps/9N140MD0NJ6T) update for testing.
At the moment the app update is certification and will be available latest tomorrow.
