### ISSUE TITLE
[bug] App crashes when you provide openHAB url without the port

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-windows#47]
Environment / device: Lumia 735

Steps to reproduce:
1. Open openHAB app
2. Press Settings button
3. Provide wrong openHAB url (in my case it was `http://192.168.0.33` without `:8080`)

Expected result:
App shows an error informing about wrong URL

Actual result:
App crashes silently 

Hey guys I wanted to thank you for your hard work! This app is a great opportunity for Windows Phone users to taste home automation system at its best :) Congratulations on your efforts!

**Comment by NicoVermeir** [comment]
thanks for the bug report and the kind words :)

**Comment by NicoVermeir** [comment]
fixed in dev branch, will go out with next release
