### ISSUE TITLE
[bug] Knob widget doesn't allow you to set "0" value

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-windows#48]
Environment / device: Lumia 735

Steps to reproduce:
1. Create a `Dimmer` item in your openHAB
2. In the Windows app try to set the minimum value for the dimmer (`0`)

Expected result:
Dimmer sets to OFF / 0

Actual result:
The item is stuck at `3`

Here's also a screenshot I made on my wife's phone :-)
Cheers!

![unnamed](https://cloud.githubusercontent.com/assets/2270505/22217608/f54379bc-e1a3-11e6-9986-cc6e5172ad91.png)

**Comment by NicoVermeir** [comment]
it can be a bit hard to get it all the way to 0 on small screen devices but it does work. I was thinking on implementing a widget tap to toggle it on / off to get around this. how does that sound?

**Comment by NicoVermeir** [comment]
next version will include toggle mode when tapping on the icon, currently in dev branch
