### ISSUE TITLE
[bug] Sitemap type setpoint not working

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-windows#50]
In my sitemap I have defined a frame with a setpoint:

```
  Frame label="Bad" {
	    Text item=HeizungBad_4_ActualTemperature   label="Aktuelle Temperatur [%s °C]" valuecolor=[>30="red",>20="orange",>15="green",>1="green",<=1="blue"]
		 Setpoint item=HeizungBad_4_SetTemperature  label="Neue Temperatur" minValue="5" maxValue="23" step="0.5"
		 Switch item=Fenster_Bad label="Fenster"
	}
```

It is display as this:
![image](https://cloud.githubusercontent.com/assets/616792/22263638/6e4b987c-e275-11e6-8417-50877724e10f.png)

**Comment by NicoVermeir** [comment]
that's because that widget hasn't been implemented yet. we focused on what we thought were the most common widgets for the first release. We'll try to get it into the next version! :)

**Comment by MHerbst** [comment]
OK :-) But in general it looks really nice. Will keep an eye on the further development.

**Comment by NicoVermeir** [comment]
setpoint widget added in dev branch, will be included in next update
