### ISSUE TITLE
Hide menu on the left side

### ISSUE THREAD

**Issue by mheiss** [openhab/openhab-windows#51]
On my mobile device (Lumia 650) the menu on the left side takes a lot of valuable space. I suggest to hide the menu by default. The store is doing the same. You just see the control to open the menu but nothing else. 

Resolution is 1280 x 720 on a 5" device. 

![wp_ss_20170205_0002](https://cloud.githubusercontent.com/assets/5145998/22626174/172c8038-eba8-11e6-87d2-a6e7f3d03b30.png)
![wp_ss_20170205_0001](https://cloud.githubusercontent.com/assets/5145998/22626173/172c2052-eba8-11e6-83d5-fa417b0324d5.png)
![wp_ss_20170205_0003](https://cloud.githubusercontent.com/assets/5145998/22626186/64145498-eba8-11e6-85ee-2fed399ae260.png)

**Comment by NicoVermeir** [comment]
implemented in dev branch, will be included in next version update
