### ISSUE TITLE
Cannot use SSL with untrusted certificates

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#65]
Setting the HTTPS URL leads to "Invalid URL, check your settings".

Windows 10 PC

**Comment by robbyb67** [comment]
same on my site

**Comment by Alex-Witkowski** [comment]
Is there an public example? 
I would like to have a look at it but don't have a https installation/server available at the moment.

**Comment by lolodomo** [comment]
The OH server is by default accessible either through HTTP on port 8080 or HTTPS on port 8443.
So you have nothing special to setup to try it.

**Comment by Alex-Witkowski** [comment]
Works for me with 
https://demo.openhab.org:8443
but not with my own installation of openhabianpi with the following error - which is correct. 
`The certificate authority is invalid or incorrect`

So we should add an option to ignore certificate errors. Or you could trust the certificate.

**Comment by tmschx** [comment]
I don't have a public example unfortunately, but I can confirm this issue. 
I am running OpenHAB 1.8.3 on an Ubuntu 14.04 server on port 8143 with a self-signed certificate.
The iOS app works like a charm using local URL "https://mydomain.net:8143", even without the option to ignore SSL-certificates, because I installed my own root certificate. 
However, the Windows app (v0.2 Beta freshly installed from app store) on a Windows 10 PC gives "Invalid URL, check your settings" with exactly the same settings. Using a browser on the same Windows 10 PC to access the rest api directly, e.g. "https://mydomain.net:8143/rest/items/sLight_Living/state" gives no problems.

**Comment by NicoVermeir** [comment]
it looks like Win10 apps don't have an option to allow untrusted certificates so I can't fix this at the moment. I'll keep looking into it to see if I can find a work-around

**Comment by lucianopeixoto** [comment]
As HTTPS actually works in certain cases, I believe @lolodomo or a collaborator should rename the issue to something like "Cannot use HTTPS URL with invalid certificates".
What do you guys think about that?

**Comment by tmschx** [comment]
I agree that it is good practice for an error message to be as accurate as possible. In my setup both URL and SSL certificates are (technically) valid, but the certificates are not trusted - at least not globally, they are by me....  A more accurate error message would then be: `Cannot use SSL with untrusted certificates`.

**Comment by tmschx** [comment]
Haven't looked deep into it yet (I am normally not into Windows related stuff), but it does seem possible to [get a vector of SSL server certificate errors that the app might subsequently choose to ignore](https://docs.microsoft.com/en-us/uwp/api/Windows.Web.Http.Filters.HttpBaseProtocolFilter#Windows_Web_Http_Filters_HttpBaseProtocolFilter_IgnorableServerCertificateErrors). That might help to improve the app, e.g. to allow untrusted certificates or some other subset of [the result of a certificate chain verification](https://docs.microsoft.com/en-us/uwp/api/Windows.Security.Cryptography.Certificates.ChainValidationResult) ...preferably as selected by the user in the app settings ofc.

**Comment by NicoVermeir** [comment]
tried that one already, made the app crash

**Comment by hoffe86** [comment]
In the meanwhile there is a possibility for the HttpClient class to override the SSL cert check. 
I implemented this option
