### ISSUE TITLE
No way to return to the parent page

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#66]
The arrow at top left allows returning to the main page but there is no way to return to the parent page.

Windows 10 PC

**Comment by lolodomo** [comment]
Strange, it seems to work well now.

**Comment by lolodomo** [comment]
I reproduce it now with the demo.

**Comment by Alex-Witkowski** [comment]
Can you please give a better description how to reproduce the issue? 
Thanks.

**Comment by lolodomo** [comment]
Very easy. Setup to use the demo. On the main page, select 'First Floor" then select "Bathroom" and finally click the left arrow at the top left of the openHAB window. You should be back to "First Floor" but you are on the main screen again.

**Comment by NicoVermeir** [comment]
I made some changes to the overall work of the app. haven't seen this issue since then, feel free to reopen once the new version is released and it should resurface
