### ISSUE TITLE
Wrong button for switch element linked to dimmer light

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#69]
If one of my dimmmer lights is ON, after opening Windows app, it looks as OFF with the button "Off" surrounding with black.

It happens only for switch elements linked to dimmer item, not for switch element linked to switch item.

Windows 10 PC

**Comment by NicoVermeir** [comment]
fixed in upcoming release

**Comment by lolodomo** [comment]
Fix confirmed.
