### ISSUE TITLE
Image item not supported

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#72]
Image element linked to an image item are apparently not supported (no image displayed).

Windows 10 PC

**Comment by NicoVermeir** [comment]
fixed in upcoming release

**Comment by lolodomo** [comment]
Not working with the last version in the store.
What is working is an image element linked a string item containing an image URL.
But what is not working is an image element linked a an image item containing the raw data of the image.

Can you please re-open the issue ?

**Comment by lolodomo** [comment]
My page with Sonos cover art is even crashing the application.

**Comment by NicoVermeir** [comment]
Thanks for the extra information, issue is reopened

**Comment by NicoVermeir** [comment]
fixed in dev branch
