### ISSUE TITLE
Text truncated for String elements

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#75]
When you have a long text in a String item, the text appears on one unique line and truncated at keft.
Maybe it could rather be truncated at right with "..." to show that it is truncated, and maybe you could display it on several lines (there is place for that).

Windows 10 PC

**Comment by hoffe86** [comment]
Text will now truncated for labels and Text Widget value should wrap and truncate (I have no item which has a value which is long enough to truncate).
![image](https://user-images.githubusercontent.com/5873390/106759981-9f7bfb80-6633-11eb-8aa0-88566ed4cac0.png)

**Comment by hoffe86** [comment]
Functionality is implemented and will be available in the [Beta app](https://www.microsoft.com/store/apps/9N140MD0NJ6T) update for testing.
At the moment the app update is certification and will be available latest tomorrow.
