### ISSUE TITLE
valuecolor conditions not taken into account

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#76]
The app seems to ignore valuecolor conditions of a sitemap element.

I have not tested the labelcolor conditions.

Windows 10 PC

**Comment by hoffe86** [comment]
Blocked by openhab/openhab-webui#324

**Comment by lolodomo** [comment]
There is nothing blocking, valurcolor conditions are available through sitemap files since years.

**Comment by hoffe86** [comment]
@lolodomo There is currently bug in OH3, which blocks me to setup a sitemap for testing

**Comment by lolodomo** [comment]
As I told you, you just have to create a sitemap file manually like everyone did before MainUI. And then you are ready for testing.

**Comment by hoffe86** [comment]
Functionality is implemented and will be available in the [Beta app](https://www.microsoft.com/store/apps/9N140MD0NJ6T) update for testing.
At the moment the app update is certification and will be available latest tomorrow.
