### ISSUE TITLE
Can't run App from within VS 2015

### ISSUE THREAD

**Issue by thilbig** [openhab/openhab-windows#9]
The build was ok. But when I start debug or release from VS 2015 the app crashes with NULL pointer exception.

**Comment by NicoVermeir** [comment]
Where does it crash?

**Comment by NicoVermeir** [comment]
Also, are you running from dev or master? And also, my own fork is way ahead of this one, I was planning on doing a PR sometime next week to get the dev branch up to date

**Comment by thilbig** [comment]
It crashed in MainViewModel.cs at line 63 "await _openHabsdk.ResetConnection();"
"Eine Ausnahme vom Typ "System.NullReferenceException" ist in mscorlib.ni.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet."

I use the master not the dev.

**Comment by NicoVermeir** [comment]
I just pushed all my changes into the dev branch, can you try again from there?

**Comment by thilbig** [comment]
I just tried the dev tree. Same as with the master. Don't know whats wrong.
Under Settings I only insert the "OpenHAB URL". I tried it with http:// and without. I used only hostnames instead of IP-Adresses. I also tried the REST website. Is this the problem?
http://<"hostname">:8080
http://<"IP-Adress">:8080
http://<"hostname">:8080/rest/sitemaps/default

I tried the demo mode. It works.

**Comment by NicoVermeir** [comment]
hmm, I'll have to investigate, haven't run into this myself
Are you running OH 1 or OH 2?

**Comment by NicoVermeir** [comment]
turns out there was an issue when running the app for the first time so no server url was set.
the dev branch should work now on a fresh device
