### ISSUE TITLE
Visibility conditions updates not considered

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#94]
If you have for example several charts with different period and a visibility condition on each chart based on the choice of period, the application is rendering the right chart at first loading. But if you make a change of period, it should trigger a new computation of the visibility condition and the change of the chart displayed. There is no change with the current version in the store.

Windows 10 PC.

**Comment by hoffe86** [comment]
Blocked by openhab/openhab-webui#324

**Comment by lolodomo** [comment]
There is nothing blocking, visibility conditions are available through sitemap files since years.

**Comment by hoffe86** [comment]
@lolodomo There is currently bug in OH3, which blocks me to setup a sitemap for testing

**Comment by lolodomo** [comment]
If you are talking about MainUI sitemap generator not supporting this feature, this is not blocking at all, you can create your sitemap in a file like we have always done since several years.

**Comment by hoffe86** [comment]
Functionality is implemented and will be available in the [Beta app](https://www.microsoft.com/store/apps/9N140MD0NJ6T) update for testing.
At the moment the app update is certification and will be available latest tomorrow.
